### ISSUE TITLE
pidgin-original-smileys

### ISSUE THREAD

**Issue by andreineculau** [Hernou/pidgin-EAP#8]
Hi!

I'm the author of the 2007 Pidgin Original Smileys, hosted since 2013 at https://github.com/andreineculau/pidgin-original-smileys

Since 2010, I've stopped using Pidgin, so the project went into "hibernation".

Just a friendly ping in case you didn't know about it and there is something to merge into your project.

**Comment by Hernou** [comment]
[See readme](https://github.com/Hernou/pidgin-EAP/blob/master/.purple/smileys/changelog) line 169 :sunglasses:
I know your project since 2008 or 2009 I think. In 2010, I sent you a new theme for the new emoticons in msn, but I didn't have an answer about this, so, with the time I created this project, and after, this git, but I didn't know that you created your own. :hushed:

Your project is the foundation of pidgin eap, so It have nothing to merge.

it's nice to hear from you and I thank you for allowing this project to exist :grinning:

**Comment by andreineculau** [comment]
On Sat, May 9, 2015 at 5:20 PM, Hernou <notifications@github.com> wrote:

> See readme
> <https://github.com/Hernou/pidgin-EAP/blob/master/.purple/smileys/changelog>
> line 169 [image: :sunglasses:]
>
Oh, I actually looked at the readme, but not at the **changelog**. I'll add
a link in my repo to yours then

> I know your project since 2008 or 2009 I think. In 2010, I sent you a new
> theme for the new emoticons in msn, but I didn't have an answer about this
>
Sorry if I didn't reply, I probably went in hibernation :)

> it's nice to hear from you and I thank you for allowing this project to
> exist [image: :grinning:]
>
Thank **you** for continuing it.


-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by Hernou** [comment]
tout le plaisir est pour moi :v:

**Comment by andreineculau** [comment]
Done. I added a cross-link to your repo
https://github.com/andreineculau/pidgin-original-smileys/commit/de2f6d5b0ecb58475ae5ddbb07cab07dbc6e80f6

On Sat, May 9, 2015 at 5:45 PM, Hernou <notifications@github.com> wrote:

> Closed #8 <https://github.com/Hernou/pidgin-EAP/issues/8>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hernou/pidgin-EAP/issues/8#event-300918432>.
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by Hernou** [comment]
thanx you :-)
